version: '3.8'

services:
# Configurar esto para arrancar los dos servicios a la vez con docker-compose up -d
  # whatyoueat:
    # build: .
    # container_name: whatyoueat_app
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # environment:
    #   - NODE_ENV=production
    # command: npm start
    # depends_on:
    #   - db

  osticket:
    image: tiredofit/osticket
    container_name: osticket
    ports:
      - "80:80"  # puerto ajustado para evitar conflictos
    environment:
      - DB_HOST=osticket_db
      - DB_NAME=osticket
      - DB_USER=osticket_user
      - DB_PASS=osticket_pass
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USER=admin123
      - ADMIN_PASS=admin123
      - ADMIN_FIRSTNAME=Admin
      - ADMIN_LASTNAME=whatyoueat
      - INSTALL_SECRET=whatyoueatsecret
      - AUTO_INSTALL=true
    depends_on:
      - osticket_db

# Configurar esto para arrancar los dos servicios a la vez con docker-compose up -d
# db:
    #   image: mysql:5.7
    #   container_name: whatyoueat_db
    #   environment:
    #     - MYSQL_DATABASE=whatyoueat
    #     - MYSQL_USER=whatyoueat_user
    #     - MYSQL_PASSWORD=whatyoueat_pass
    #     - MYSQL_ROOT_PASSWORD=rootpassword
    #   volumes:
    #     - db_data:/var/lib/mysql

  osticket_db:
    image: mysql:5.7
    container_name: osticket_db
    environment:
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket_user
      - MYSQL_PASSWORD=osticket_pass
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - osticket_db_data:/var/lib/mysql

volumes:
  db_data:
  osticket_db_data: